### ISSUE TITLE
da nya cupu. ini issue yang bermasalah.

### ISSUE THREAD

**Issue by plty** [DanielAWidjaja/42schoolsiliconvalley#2]
# pleb.

**Comment by rwhendry** [comment]
setuju, ini patut di fix DA nya

**Comment by plty** [comment]
@rwhendry udah 18 tahun belom ada fix.

**Comment by rwhendry** [comment]
@plty kaga bisa di fix mah ini , udah ga tertolong

**Comment by smsunarto** [comment]
Unfixable, please close this issue

**Comment by plty** [comment]
@smsunarto noted.
